import { ApolloWrapper } from '@/providers/ApolloProvider'
import { GoogleOAuthProvider } from '@react-oauth/google'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html
         lang="en"
         className={'antialiased'}
      >
         <body className="font-helvetica-roman bg-neutro-2">
            <GoogleOAuthProvider
               clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
               locale="es"
            >
               <ApolloWrapper>{children}</ApolloWrapper>
            </GoogleOAuthProvider>
         </body>
      </html>
   )
}
